import { ResizablePanel, ResizablePanelGroup } from "@repo/ui/resizable";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import SideNav from "../../components/dashboard/sideNav";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <main>
      <ResizablePanelGroup
        direction="horizontal"
        className="w-100 h-100"
      >
        <ResizablePanel defaultSize={15} minSize={4}>
          <div className="flex items-center justify-center h-screen border-r border-muted">
            <SideNav />
          </div>
        </ResizablePanel>
        <ResizablePanel defaultSize={85}>
          <ResizablePanelGroup direction="vertical" className="w-full h-full">
            <ResizablePanel defaultSize={100} className="!overflow-y-auto">
              <div className="flex w-100 h-100 py-4 px-4">
                {children}
              </div>
            </ResizablePanel>
          </ResizablePanelGroup>
        </ResizablePanel>
      </ResizablePanelGroup >
    </main >
  );
}
